//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStoreApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsSold
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Product { get; set; }
        public int Amount { get; set; }
        public int SellinPrice { get; set; }
        public int SumOfSale { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
